### ISSUE TITLE
Suggestion: A different approach

### ISSUE THREAD

**Issue by Silanael** [ardriveapp/ardrive-core-js#76]
There have been a few too many instances where people's files, folders and even drives have disappeared.
While bundling will make these situations less likely, they cannot be completely eliminated with the current model.

I recommend that all the development of ArFS-functionality is done with the assumption that metadata IS missing.

See no drives upon first launch? Search for file and folder entries anyways.
Find orphaned files? Offer to fix them or display them in a Lost and found -section.
The client's cached state differs from the state in Arweave? Reconstruct missing metadata entries.

To us devs, the issue of files not being displayed correctly seems trivial - we know that the data is likely intact.
But when looking from the perspective of running a business, these occurrences are absolutely disastrous.

A service advertising to store data forever should NEVER EVER, not under any circumstances, look like it's doing the very thing it swore to fight against.

Reliability and robustness > rushing out new features.
Add failsafes upon failsafes. Let's show people that the delete-button is deleted for real.

**Comment by agsuy** [comment]
This has been digested and converted into tickets internally.

Thanks for the feedback. Closing this.
